//
//  dashboardInteractor.swift
//  VIP Pattern Training
//
//  Created by APCMB002 on 04/05/19.
//  Copyright (c) 2019 APCMB002. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol dashboardBusinessLogic
{
  func doSomething(request: dashboard.Something.Request)
}

protocol dashboardDataStore
{
  //var name: String { get set }
}

class dashboardInteractor: dashboardBusinessLogic, dashboardDataStore
{
    var presenter: dashboardPresentationLogic?
    var worker: dashboardWorker?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething(request: dashboard.Something.Request)
    {
        worker = dashboardWorker()
        worker?.doSomeWork()
        
        let response = dashboard.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
