//
//  dashboardPresenter.swift
//  VIP Pattern Training
//
//  Created by APCMB002 on 04/05/19.
//  Copyright (c) 2019 APCMB002. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol dashboardPresentationLogic
{
  func presentSomething(response: dashboard.Something.Response)
}

class dashboardPresenter: dashboardPresentationLogic
{
  weak var viewController: dashboardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: dashboard.Something.Response)
  {
    let viewModel = dashboard.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
