//
//  SettingsInteractor.swift
//  VIP Pattern Training
//
//  Created by Adli Raihan on 02/05/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsBusinessLogic
{
  func doSomething(request: Settings.Something.Request)
}

protocol SettingsDataStore
{
  var name: String { get set }
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore
{
    var name: String = ""
    
  var presenter: SettingsPresentationLogic?
  var worker: SettingsWorker?
  //var name: String = ""
  
  // MARK: Do something
    
  func doSomething(request: Settings.Something.Request)
  {
    worker = SettingsWorker()
    worker?.doSomeWork()
    
    var response = Settings.Something.Response()
    response.thisResponseJS = name
    presenter?.presentSomething(response: response)
  }
}
