//
//  HomeWorker.swift
//  VIP Pattern Training
//
//  Created by Adli Raihan on 02/05/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ObjectMapper

class HomeWorker
{
    // MARK: Testing API using MOYA !
    func testAPI(request: Home.Profile.Request,completion Completion : @escaping (Any?,Bool) -> Void) {
        provider.request(.getProfile(userId: "123")) { (result) in
            
            switch result
            {
                
            case .success(let response):
                
                do {
                    let data = try response.mapJSON()
                    
                    // Try Method
                    if let data = data as? [String:Any] , !data.isEmpty {
                        let profile =  profileMapper(JSON: data)

                        Completion(profile,true)
                    }
                    
                }
                catch
                {
                    Completion(nil,false)
                }
                
                print("#Response \(String(describing: response.data))")
                break
                
                
            case .failure(let error):
                print("#Error \(error)")
                break
            }
        }
    }
}
