//
//  HomeModels.swift
//  VIP Pattern Training
//
//  Created by Adli Raihan on 02/05/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
      enum Profile
      {
        struct Request
        {
            var userIDProfile : String?
        }
        
        struct Response
        {
            var username : String?
            var email   : String?
            var userId : Int?
        }
        
        struct ViewModel
        {
            var controllerName : String?
        }
      }
    
    enum Something
    {
        struct Request
        {
            var userIDProfile : String?
        }
        struct Response
        {
        }
        struct ViewModel
        {
            var controllerName : String?
        }
    }
}
