//
//  HomePresenter.swift
//  VIP Pattern Training
//
//  Created by Adli Raihan on 02/05/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentSomething(response: Home.Profile.Response)
    func presentRouting ()
}

class HomePresenter: HomePresentationLogic
{
    
    
    
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
    func presentSomething(response: Home.Profile.Response) {
        
        var viewModel = Home.Profile.ViewModel()
        
        // * Initialize *
        viewModel.controllerName = response.username
        
        viewController?.displaySomething(viewModel: viewModel)
    
    }
    
    
    func presentRouting () {
        viewController?.routeToSettings()
    }
}
